CREATE TABLE  ROLES (
  ROLE_ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(20) NOT NULL,
  PRIMARY KEY (ROLE_ID));


CREATE TABLE  USER_ROLE (
  ROLE_ID INT NOT NULL,
  ID INT NOT NULL,
  PRIMARY KEY (ROLE_ID, ID));
